title:
default_locale: "cs"
permalink: pretty
markdown: kramdown
facebookurl: https://www.facebook.com/piratitabor
logo: /static/logo_cb3.svg

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate: 7
paginate_path: "/clanky/:num/"
articlepath: blog
keywords: českobudějovicko,piráti
url: https://cb.pirati.cz
